### ISSUE TITLE
TDD in Python with pytest - Part 1 (additional refactoring)

### ISSUE THREAD

**Issue by labdmitriy** [TheDigitalCatOnline/blog_source#10]
Hi Leonardo,

In [this section](https://thedigitalcatonline.com/blog/2020/09/10/tdd-in-python-with-pytest-part-1/#step-6---refactoring) you provided refactored code for multiplication with lambda function:
```python
from functools import reduce


class SimpleCalculator:
    [...]

    def mul(self, *args):
        return reduce(lambda x, y: x*y, args)
```

My note is not related to the testing itself, but maybe it will be useful - we can also use `mul` function from the standard `operator` package to have the following code:
```python
from functools import reduce
from operator import mul

class SimpleCalculator:
    [...]

    def mul(self, *args):
        return reduce(mul, args)
```

Thank you.

**Comment by lgiordani** [comment]
A nice suggestion! I will incorporate it, thanks :top:
