### ISSUE TITLE
motorola-68000-addressing-modes register swap

### ISSUE THREAD

**Issue by rolsen74** [TheDigitalCatOnline/blog_source#15]
In your blog about 68000 Addressing modes you have swap two regitsers
 
<---

Address Register Indirect with Index

    Assembly syntax: (d8,Dn,An)  <-- Here
    EA Mode field: 110
    EA Register field: Register number
    Extension words: 1

<---

The correct mode is (d8,An,Dn) or (d8,An,Xn) as written in M68000 FAMILY PROGRAMMER’S REFERENCE MANUAL.

You also have it swap in this line..

cmpi.w  #0x1111,(0x4,d0,a1)

A few line futher down, you get it correct..

(d8, An, Dn.SIZE)

Anyway thanks for the blog post.. I used it to verify some of my currect work.

**Comment by lgiordani** [comment]
Blimey! Well, thanks, I completely missed that. I will fix it shortly.
Thanks a lot, what are you working on?

**Comment by rolsen74** [comment]
I am writting an Amiga Exe Binary file resourcer/disassembler .. basicly turning an exe into assembler source code..

And I'm currently looking into the 68020+ addressing modes. .. And I used your blog to verify my 68000 modes

**Comment by lgiordani** [comment]
Thanks! I fixed it. And congrats for the resrc4 project, very nice!
