### ISSUE TITLE
Long blog post shown incompletely

### ISSUE THREAD

**Issue by L-Ron-GitHubbard** [TheDigitalCatOnline/blog_source#22]
Thanks for writing an excellent guide on Pelican themes:
https://blog.thedigitalcatonline.com/blog/2021/03/25/how-to-write-a-pelican-theme-for-your-static-website/

I was reading and following along with your steps when the article shown in my browser suddenly just ended after:

> We need to replace the static text with this variable three times: in the tag 

I observe the same behavior (issue) when the page is viewed in the latest versions of desktop Firefox and Edge, and also Firefox mobile.

Looking at the source of the page, it actually has a lot more content. What you wrote is just is not fully shown on your blog website. 

So on the one hand I want to inform you of that issue. On the other, I would much rather read the rest of that blog post in the intended format, rather than reading it in source code.

Hope this helps!

**Comment by lgiordani** [comment]
Hi! You are right I can confirm that. I will investigate as soon as possible and (hopefully) solve it. Thanks for submitting the issue! :top:

**Comment by lgiordani** [comment]
OK, that was simple but nasty. Mau renders code without replacing characters with HTML entities so `<title>` was literal and made a mess in the page. I will work on it, but for now it was enough to replace it with `$lt;title&gt;`. Thanks, I will close this issue now.
