### ISSUE TITLE
A possible typo or meaning issue

### ISSUE THREAD

**Issue by thomasdick-tortuetec** [TheDigitalCatOnline/blog_source#25]
TDD in Python with pytest - Part 3 > Focus on messages > Message flow > first sentence:

Change (source, ~~origin~~) to (source, **destination**)?

**Comment by lgiordani** [comment]
Blimey, that has been there for a very long time! :joy_cat: Thanks, I'm going to fix it now

**Comment by lgiordani** [comment]
Thanks @thomasdick-tortuetec!
