### ISSUE TITLE
lack of licensing

### ISSUE THREAD

**Issue by nunogrl** [TheDigitalCatOnline/blog_source#3]
Hello I was checking for existing pelican blog websites and I was pleased to see how you adapted so well a template to your needs.
Is this project open source? if that's the case what kind of license would best describe it?

Thanks

**Comment by lgiordani** [comment]
Hi @nunogrl the whole blog is actually open source. The content is CC BY-SA 4.0 (https://github.com/TheDigitalCatOnline/blog_source/blob/master/pelican/content/pages/about.markdown), the source of the `editorial` theme is not explicitly released as a separate repository, but feel free to grab it and reuse it. I think a MIT license is the one I would adopt.

**Comment by nunogrl** [comment]
wow! Thank you for the quick reply!
Your blog motivated me to create one of my own.

Thanks for clarifying this

**Comment by lgiordani** [comment]
Thanks! You might be interested in this post then https://www.thedigitalcatonline.com/blog/2019/06/07/run-a-pelican-blog/. The whole setup is a bit rusty and old, but it should at least be easy to run
